<a href="https://colab.research.google.com/github/antonyrajesh123/Session19/blob/main/Session19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# GridWorld size
GRID_SIZE = 4
NUM_STATES = GRID_SIZE * GRID_SIZE
ACTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Up, Down, Left, Right
GAMMA = 1.0
THRESHOLD = 1e-4

# Initialize Value Function
V = np.zeros(NUM_STATES)

def get_next_states(state):
    """Returns possible next states from the given state."""
    x, y = divmod(state, GRID_SIZE)
    next_states = []

    for dx, dy in ACTIONS:
        nx, ny = x + dx, y + dy
        if 0 <= nx < GRID_SIZE and 0 <= ny < GRID_SIZE:
            next_states.append(nx * GRID_SIZE + ny)  # Convert (x, y) to state index
        else:
            next_states.append(state)  # Stay in the same state if out of bounds

    return next_states

# Value Iteration
while True:
    delta = 0
    V_new = np.copy(V)

    for state in range(NUM_STATES):
        if state == NUM_STATES - 1:  # Terminal state (bottom-right corner)
            continue

        next_states = get_next_states(state)
        expected_value = np.mean([-1 + GAMMA * V[s] for s in next_states])  # Bellman update

        delta = max(delta, abs(expected_value - V[state]))  # Track max change
        V_new[state] = expected_value

    V = V_new

    if delta < THRESHOLD:  # Convergence condition
        break

# Print final value function
V_grid = V.reshape((GRID_SIZE, GRID_SIZE))
print("Optimal Value Function:")
print(V_grid)



Optimal Value Function:
[[-59.42367735 -57.42387125 -54.2813141  -51.71012579]
 [-57.42387125 -54.56699476 -49.71029394 -45.13926711]
 [-54.2813141  -49.71029394 -40.85391609 -29.99766609]
 [-51.71012579 -45.13926711 -29.99766609   0.        ]]
